name: Ejecutar Pruebas Karate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del código
      uses: actions/checkout@v4
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Configurar Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Descargar Karate JAR
      run: |
        curl -L -o karate.jar https://github.com/karatelabs/karate/releases/download/v1.5.1/karate-1.5.1.jar
    - name: Ejecutar pruebas Karate
      run: java -cp karate.jar com.intuit.karate.Main src/test/resources/github-api.feature
    - name: Subir reportes como artefactos
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: karate-reports
        path: target/karate-reports/